spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3305/test_db
    username: test
    password: test_pw

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties.hibernate.format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
#      mode: never
      mode: always

  redis:
    host: localhost
    port: 6378

  jwt:
    secret: ${JWT_KEY}

custom:
  sms:
    api-key: ${SMS_API_KEY}
    api-secret: ${SMS_API_SECRET}
    source: ${SMS_SOURCE}